export const LOG_CONNECT = "LOG_CONNECT";
export const LOG_SUCCES = "LOG_SUCCES";
export const LOG_FAIL = "LOG_FAIL";

export const CONTACTS_CONNECT = "CONTACTS_CONNECT";
export const CONTACTS_SUCCES = "CONTACTS_SUCCES";
export const CONTACTS_FAIL = "CONTACTS_FAIL";

export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_CONTACT_SUCCES = "ADD_CONTACT_SUCCES";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";

export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const REMOVE_CONTACT_SUCCES = "REMOVE_CONTACT_SUCCES";
export const REMOVE_CONTACT_FAIL = "REMOVE_CONTACT_FAIL";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_SUCCES = "UPDATE_CONTACT_SUCCES";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";
